// src/api/endpoints.js

var ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
    VERIFY_EMAIL: '/auth/verify-email',
    SEND_OTP: '/auth/send-otp',
    VERIFY_OTP: '/auth/verify-otp',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    CHANGE_PASSWORD: '/auth/change-password',
  },
  USERS: {
    PROFILE: function (username) { return '/users/' + username; },
    UPDATE_PROFILE: '/users/profile',
    FOLLOW: function (id) { return '/users/' + id + '/follow'; },
    FRIEND_REQUEST: function (id) { return '/users/' + id + '/friend-request'; },
    ACCEPT_FRIEND: function (id) { return '/users/' + id + '/accept-friend'; },
    DECLINE_FRIEND: function (id) { return '/users/' + id + '/decline-friend'; },
    UNFRIEND: function (id) { return '/users/' + id + '/unfriend'; },
    BLOCK: function (id) { return '/users/' + id + '/block'; },
    UNBLOCK: function (id) { return '/users/' + id + '/unblock'; },
    FOLLOWERS: function (id) { return '/users/' + id + '/followers'; },
    FOLLOWING: function (id) { return '/users/' + id + '/following'; },
    FRIENDS: function (id) { return '/users/' + id + '/friends'; },
    BLOCKED: '/users/blocked',
    SUGGESTIONS: '/users/suggestions',
    DELETE_ACCOUNT: '/users/account',
  },
  POSTS: {
    FEED: '/posts/feed',
    TRENDING: '/posts/trending',
    CREATE: '/posts',
    GET: function (id) { return '/posts/' + id; },
    EDIT: function (id) { return '/posts/' + id; },
    DELETE: function (id) { return '/posts/' + id; },
    SHARE: function (id) { return '/posts/' + id + '/share'; },
    SAVE: function (id) { return '/posts/' + id + '/save'; },
    USER_POSTS: function (id) { return '/posts/user/' + id; },
    REPORT: function (id) { return '/posts/' + id + '/report'; },
  },
  COMMENTS: {
    GET: function (postId) { return '/comments/post/' + postId; },
    CREATE: function (postId) { return '/comments/post/' + postId; },
    REPLY: function (id) { return '/comments/' + id + '/reply'; },
    EDIT: function (id) { return '/comments/' + id; },
    DELETE: function (id) { return '/comments/' + id; },
    REPORT: function (id) { return '/comments/' + id + '/report'; },
  },
  REACTIONS: {
    POST: function (id) { return '/reactions/post/' + id; },
    COMMENT: function (id) { return '/reactions/comment/' + id; },
    GET: function (type, id) { return '/reactions/' + type + '/' + id; },
    LIST: function (type, id) { return '/reactions/' + type + '/' + id + '/list'; },
  },
  STORIES: {
    FEED: '/stories/feed',
    CREATE: '/stories',
    VIEW: function (id) { return '/stories/' + id + '/view'; },
    REACT: function (id) { return '/stories/' + id + '/react'; },
    VIEWERS: function (id) { return '/stories/' + id + '/viewers'; },
    DELETE: function (id) { return '/stories/' + id; },
    HIGHLIGHTS: function (id) { return '/stories/highlights/' + id; },
    MARK_HIGHLIGHT: function (id) { return '/stories/' + id + '/highlight'; },
  },
  MESSAGES: {
    CONVERSATIONS: '/messages/conversations',
    CREATE_CONVERSATION: '/messages/conversations',
    GET_MESSAGES: function (id) { return '/messages/conversations/' + id; },
    SEND: function (id) { return '/messages/conversations/' + id; },
    READ: function (id) { return '/messages/conversations/' + id + '/read'; },
    DELETE: function (id) { return '/messages/' + id; },
    MUTE: function (id) { return '/messages/conversations/' + id + '/mute'; },
    UNMUTE: function (id) { return '/messages/conversations/' + id + '/unmute'; },
    CLEAR: function (id) { return '/messages/conversations/' + id; },
    SETTINGS: '/messages/settings',
  },
  GROUPS: {
    LIST: '/groups',
    MY: '/groups/my',
    CREATE: '/groups',
    GET: function (id) { return '/groups/' + id; },
    UPDATE: function (id) { return '/groups/' + id; },
    DELETE: function (id) { return '/groups/' + id; },
    JOIN: function (id) { return '/groups/' + id + '/join'; },
    LEAVE: function (id) { return '/groups/' + id + '/leave'; },
    APPROVE: function (id, userId) { return '/groups/' + id + '/requests/' + userId; },
    POSTS: function (id) { return '/groups/' + id + '/posts'; },
    CREATE_POST: function (id) { return '/groups/' + id + '/posts'; },
    DELETE_POST: function (groupId, postId) { return '/groups/' + groupId + '/posts/' + postId; },
  },
  MARKETPLACE: {
    LIST: '/marketplace',
    CREATE: '/marketplace',
    GET: function (id) { return '/marketplace/' + id; },
    EDIT: function (id) { return '/marketplace/' + id; },
    DELETE: function (id) { return '/marketplace/' + id; },
    SAVE: function (id) { return '/marketplace/' + id + '/save'; },
  },
  NOTIFICATIONS: {
    LIST: '/notifications',
    UNREAD_COUNT: '/notifications/unread-count',
    READ: function (id) { return '/notifications/' + id + '/read'; },
    READ_ALL: '/notifications/read-all',
    DELETE: function (id) { return '/notifications/' + id; },
    PREFERENCES: '/notifications/preferences',
  },
  SEARCH: {
    ALL: '/search',
    TRENDING: '/search/trending',
    HASHTAGS: '/search/hashtags',
    HASHTAG: function (tag) { return '/search/hashtag/' + tag; },
    SUGGESTIONS: '/search/suggestions',
  },
  SETTINGS: {
    GET: '/settings',
    PRIVACY: '/settings/privacy',
    NOTIFICATIONS: '/settings/notifications',
    ADS: '/settings/ads',
  },
  VERIFICATION: {
    APPLY: '/verification/apply',
    STATUS: '/verification/status',
    PAYMENTS: '/verification/payments',
  },
  PAYMENT: {
    METHODS: '/public/payments',
    STRIPE_CHECKOUT: '/payment/stripe',
    MPESA_STK: '/payment/mpesa',
    MPESA_MANUAL: '/payment/manual',
  },
  ADS: {
    PREFERENCES: '/ads/preferences',
    CONSENT: '/ads/consent',
  },
  REPORTS: {
    CREATE: '/reports',
  },
  BACKUP: {
    REQUEST: '/backup/request',
    LIST: '/backup',
  },
  REELS: {
    LIST: '/reels',
    CREATE: '/reels',
    REACT: function (id) { return '/reels/' + id + '/react'; },
    DELETE: function (id) { return '/reels/' + id; },
  },
  PUBLIC: {
    LEGAL: function (key) { return '/public/legal/' + key; },
    PAYMENTS: '/public/payments',
  },
};

export { ENDPOINTS };